/*This file is small but important—it’s your “contract” between build and runtime
    - globDirectory: where Workbox looks for files to precache(your built app in wwwroot /).
    - globPatterns: which file types to include in the precache manifest(you can tweak this later).
    - swSrc: your source service worker file(what you edit).
    - swDest: the actual file the app uses(service - worker.published.js), generated by Workbox.
*/

module.exports = {
    globDirectory: "wwwroot/",
    globPatterns: [
        "**/*.{html,js,css,json,png,svg,ico}"
    ],
    swSrc: "service-worker-src.js",
    swDest: "wwwroot/service-worker.published.js"
};